import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser=process.argv[2]?await chromium.connectOverCDP(process.argv[2]):await chromium.launch({headless:true});
const page=process.argv[2]?browser.contexts()[0].pages().find(p=>p.url().includes('localhost:5173')):await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.waitForFunction(()=>!!window.__golfTest);await page.click('#audio-toggle');await page.click('#play');await page.click('#begin');
await page.evaluate(()=>{const g=window.__golfTest;g.clearEnemies();g.phase='combat';g.spawnTime=100;g.enemyBudget=100;g.enemiesSpawned=0;g.combatTime=0;g.player.root.position.set(0,8,40);g.ball.position.set(15,8,190);g.cameraYaw=0;g.player.root.rotation.y=0;g.updateCamera(10);});
await page.keyboard.down('KeyC');await page.keyboard.down('KeyD');await page.waitForTimeout(400);await page.keyboard.up('KeyD');
let state=await page.evaluate(()=>window.ninjaGolf.state());assert.ok(state.player[0]<-1);assert.ok(Math.abs(state.facing)<.08,'Focused strafe keeps facing forward');
const before=state.player[2];await page.keyboard.down('KeyS');await page.waitForTimeout(400);await page.keyboard.up('KeyS');await page.keyboard.up('KeyC');state=await page.evaluate(()=>window.ninjaGolf.state());assert.ok(state.player[2]<before-1);assert.ok(Math.abs(state.facing)<.08,'Focused backpedal keeps facing forward');
// A left attack must not release a held right-button stance.
await page.mouse.move(720,440);await page.mouse.down({button:'right'});await page.mouse.click(720,440,{button:'left'});await page.waitForFunction(()=>window.__golfTest.action?.kind==='light');assert.ok(await page.evaluate(()=>window.__golfTest.input.focused));await page.mouse.up({button:'right'});await page.waitForFunction(()=>!window.__golfTest.action);await page.evaluate(()=>{window.__golfTest.lightChain=0;});
// Buffer the second light attack, then branch to its heavy finisher.
await page.keyboard.press('KeyJ');await page.waitForTimeout(160);await page.keyboard.press('KeyJ');await page.waitForFunction(()=>window.__golfTest.action?.step===1);await page.keyboard.press('KeyK');await page.waitForFunction(()=>window.__golfTest.action?.kind==='heavy');assert.equal(await page.evaluate(()=>window.__golfTest.action.name),'Skyward finish');
await page.waitForFunction(()=>!window.__golfTest.action);
await page.evaluate(()=>{const g=window.__golfTest;g.resolve=100;});await page.keyboard.press('KeyL');await page.waitForFunction(()=>window.__golfTest.cinematic>0);await page.waitForTimeout(250);await page.screenshot({path:'/tmp/ninja-musou.png'});await page.waitForFunction(()=>window.__golfTest.action?.kind==='musou');await page.waitForTimeout(350);await page.screenshot({path:'/tmp/ninja-musou-strike.png'});await page.waitForFunction(()=>!window.__golfTest.action);
// Every emergence has a real site and a finite trajectory, including hazards.
for(const kind of ['lantern','pagoda','rock','tree','sand','water']){
 const result=await page.evaluate(async kind=>{const {lieAt}=await import('/src/course.js');const g=window.__golfTest;g.paused=true;g.clearEnemies();g.time+=10;const site=g.world.ambushSites.find(s=>s.kind===kind);const saved=g.world.ambushSites;g.world.ambushSites=[site];g.player.root.position.set(site.x,site.y,site.z-25);g.ball.position.set(site.x,site.y,site.z+50);g.enemiesSpawned=0;g.spawnWave(1);g.world.ambushSites=saved;const e=g.enemies[0];if(!e)return {missing:kind};const initial={visible:e.root.visible,site:e.spawnSite};for(let i=0;i<90;i++)g.updateCombat(1/60);g.crowd.update(g.enemies);return{...initial,kind,emerged:!e.emerging,finite:e.root.position.toArray().every(Number.isFinite),lie:lieAt(g.course,e.root.position.x,e.root.position.z)};},kind);
 assert.ok(!result.missing,JSON.stringify(result));assert.equal(result.visible,false);assert.ok(result.site.startsWith(kind));assert.ok(result.emerged);assert.ok(result.finite);assert.notEqual(result.lie,'Water');
}
// Standard gamepad: LT strafe, X light, Y heavy, RB Musou.
await page.evaluate(()=>{const g=window.__golfTest;g.clearEnemies();g.player.root.position.set(0,8,45);g.ball.position.set(0,8,180);g.cameraYaw=0;g.player.root.rotation.y=0;g.updateCamera(10);g.spawnTime=100;g.paused=false;window.testPad={axes:[1,0,0,0],buttons:Array.from({length:16},()=>({pressed:false,value:0}))};window.testPad.buttons[6].pressed=true;Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[window.testPad]});});
await page.waitForTimeout(300);assert.ok(Math.abs((await page.evaluate(()=>window.ninjaGolf.state())).facing)<.08);await page.evaluate(()=>{window.testPad.axes[0]=0;window.testPad.buttons[3].pressed=true;});await page.waitForFunction(()=>window.__golfTest.action?.kind==='heavy');await page.evaluate(()=>{window.testPad.buttons[3].pressed=false;});await page.waitForFunction(()=>!window.__golfTest.action);await page.evaluate(()=>{window.__golfTest.resolve=100;window.testPad.buttons[5].pressed=true;});await page.waitForFunction(()=>window.__golfTest.cinematic>0);await page.evaluate(()=>{delete navigator.getGamepads;window.__golfTest.paused=true;window.__golfTest.audio.pause();});
assert.deepEqual(errors,[]);console.log('Focused strafe/backpedal, buffered finishers, Musou, six scenery entrances and gamepad controls passed');await browser.close();
