import * as THREE from 'three';
export function segmentDistanceSquared(a,b,p){const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z;const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy+(p.z-a.z)*dz)/(dx*dx+dy*dy+dz*dz||1)));return(p.x-a.x-dx*t)**2+(p.y-a.y-dy*t)**2+(p.z-a.z-dz*t)**2;}
export function sphereHitTime(a,b,center,radius){const x=a.x-center.x,y=a.y-center.y,z=a.z-center.z,dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,c=x*x+y*y+z*z-radius*radius;if(c<=0)return 0;const aa=dx*dx+dy*dy+dz*dz;if(aa<1e-12)return null;const dot=x*dx+y*dy+z*dz,disc=dot*dot-aa*c;if(disc<0)return null;const t=(-dot-Math.sqrt(disc))/aa;return t>=0&&t<=1?t:null;}
export class Projectiles{
  constructor(scene,effects){this.scene=scene;this.effects=effects;this.items=[];const shape=new THREE.Shape();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?.065:.24,x=Math.cos(a)*r,y=Math.sin(a)*r;i?shape.lineTo(x,y):shape.moveTo(x,y);}shape.closePath();this.geometry=new THREE.ShapeGeometry(shape);this.material=new THREE.MeshStandardMaterial({color:'#e5ded0',emissive:'#805021',emissiveIntensity:.5,metalness:.8,roughness:.3,side:THREE.DoubleSide});}
  spawn(origin,target,damage,attacker=null){if(this.items.length>=32)return;const mesh=new THREE.Mesh(this.geometry,this.material);mesh.position.copy(origin);this.scene.add(mesh);this.items.push({mesh,velocity:target.clone().sub(origin).normalize().multiplyScalar(14),damage,attacker,life:2.2,trail:0});}
  update(dt,player,hurt,collision=null){const center=player.clone().add(new THREE.Vector3(0,1,0));for(let i=this.items.length-1;i>=0;i--){const p=this.items[i],before=p.mesh.position.clone();p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.rotation.z+=dt*24;p.life-=dt;p.trail+=dt;if(p.trail>.045){this.effects.burst(p.mesh.position,2,.2,0);p.trail=0;}const wall=collision?.sweepSphere(before,p.mesh.position,.12,true),playerTime=sphereHitTime(before,p.mesh.position,center,.55),hit=playerTime!==null&&(!wall||playerTime<wall.t);if(hit)hurt(p.damage,before,p.attacker);if(wall&&!hit){p.mesh.position.lerpVectors(before,p.mesh.position,wall.t);this.effects.burst(p.mesh.position,8,2,0);}if(hit||wall||p.life<=0){this.scene.remove(p.mesh);this.items.splice(i,1);}}}
  clear(){for(const p of this.items)this.scene.remove(p.mesh);this.items=[];}
}
