// Combat styles identify existing animation families; weaponKind selects the current blade geometry.
export const WARRIORS = [
  { model: 'ronin', selectionClip: 'Ronin_Selection_Idle', combatStyle: 'odachi', motionPrefix: '', readyClip: 'Ronin_Ready', motionOverrides: { Cut_Diagonal: 'Ronin_Driving_Cut', Heavy_Cleave: 'Ronin_Power_Cut' }, weaponKind: 'odachi', dualWield: false, name: 'The Ronin', title: 'Master of the long game', color: '#bc493c', power: 1.08, speed: 1, damage: 1.2, health: 110, precision: .95, weapon: 'Odachi', special: 'Crimson cyclone', description: 'A powerful drive. A devastating blade. Still working on his short game.', stats: [92, 68, 86] },
  { model: 'shinobi', selectionClip: 'Twin_Selection_Idle', combatStyle: 'twin', motionPrefix: 'Twin_', readyClip: 'Twin_Ready', weaponKind: 'twin', dualWield: true, name: 'The Shinobi', title: 'Quiet feet. Questionable handicap.', color: '#6ca3aa', power: .93, speed: 1.23, damage: .95, health: 90, precision: 1.3, weapon: 'Twin blades', special: 'Shadow storm', description: 'Quick across the rough, precise on the green. Disappears after a bogey.', stats: [68, 96, 76] },
  { model: 'monk', selectionClip: 'Naginata_Selection_Idle', combatStyle: 'naginata', motionPrefix: 'Naginata_', readyClip: 'Ethan_Naginata_Ready', motionOverrides: { Naginata_Cut_Diagonal: 'Ethan_Naginata_Driving_Cut', Naginata_Cut_Return: 'Ethan_Naginata_Cut_Return', Naginata_Cut_Rising: 'Ethan_Naginata_Cut_Rising', Naginata_Cut_Sweep: 'Ethan_Naginata_Cut_Sweep', Naginata_Heavy_Cleave: 'Ethan_Naginata_Power_Cut', Naginata_Heavy_Rising: 'Ethan_Naginata_Heavy_Rising', Naginata_Heavy_Sweep: 'Ethan_Naginata_Heavy_Sweep', Naginata_Heavy_Slam: 'Ethan_Naginata_Heavy_Slam', Naginata_Musou_Flow: 'Ethan_Naginata_Musou_Flow' }, weaponKind: 'naginata', dualWield: false, name: 'The Vice President', title: 'This meeting could have been a birdie.', color: '#dcad57', power: 1, speed: .94, damage: 1.4, health: 140, precision: 1.12, weapon: 'Naginata', special: 'Hostile takeover', description: 'Ethan Cary brings executive authority to the municipal links. Every ambush becomes an unscheduled restructuring.', stats: [80, 80, 96] },
  { model: 'kaede', selectionClip: 'Fan_Selection_Idle', combatStyle: 'fan', motionPrefix: 'Fan_', readyClip: 'Ace_Ready', motionOverrides: { Fan_Cut_Diagonal: 'Ace_Cut_Diagonal', Fan_Heavy_Cleave: 'Ace_Heavy_Cleave' }, weaponKind: 'jian', dualWield: false, name: 'The Ace', title: 'Course record. Incident report.', color: '#cc6175', power: 1.05, speed: 1.08, damage: 1.12, health: 105, precision: 1.1, weapon: 'Jian · straight sword', special: 'Petal tempest', description: 'A tour captain with a precise straight sword and graceful countersteps. Her etiquette is sharper than her putting.', stats: [88, 83, 82] },
  { model: 'ayame', selectionClip: 'Ring_Selection_Idle', combatStyle: 'ring', motionPrefix: 'Ring_', readyClip: 'Ring_Ready', motionOverrides: { Ring_Cut_Diagonal: 'Hustler_Diagonal_Cut' }, weaponKind: 'dao', dualWield: false, name: 'The Hustler', title: 'Your handicap is negotiable.', color: '#9e8cce', power: .96, speed: 1.2, damage: 1, health: 95, precision: 1.28, weapon: 'Dao · curved sabre', special: 'Violet orbit', description: 'A match-play tactician with a curved sabre and quick changes of direction. Takes every dogleg personally.', stats: [73, 95, 80] },
  { model: 'sora', selectionClip: 'Sickle_Selection_Idle', combatStyle: 'sickle', motionPrefix: 'Sickle_', readyClip: 'Sickle_Ready', weaponKind: 'wakizashi', dualWield: false, name: 'The Closer', title: 'Always makes the cut.', color: '#6caf9c', power: 1.03, speed: 1, damage: 1.3, health: 125, precision: 1.18, weapon: 'Wakizashi · short sword', special: 'Jade harvest', description: 'A quiet links hunter with a short sword, low footwork, and a dry sense of humor. Always makes the cut.', stats: [84, 88, 91] },
];

// Keep persistent hero IDs stable; arrange the selection cards independently.
export const WARRIOR_SELECTION_ORDER=[0,3,1,4,2,5];
