// Combat styles identify existing animation families; weaponKind selects the current blade geometry.
export const WARRIORS = [
  { model: 'ronin', selectionClip: 'Ronin_Selection_Idle', combatStyle: 'odachi', motionPrefix: '', readyClip: 'Ready', weaponKind: 'odachi', dualWield: false, name: 'The Ronin', title: 'Master of the long game', color: '#bc493c', power: 1.08, speed: 1, damage: 1.2, health: 110, precision: .95, weapon: 'Odachi', special: 'Crimson cyclone', description: 'A powerful drive. A devastating blade. Still working on his short game.', stats: [92, 68, 86] },
  { model: 'shinobi', selectionClip: 'Twin_Selection_Idle', combatStyle: 'twin', motionPrefix: 'Twin_', readyClip: 'Twin_Ready', weaponKind: 'twin', dualWield: true, name: 'The Shinobi', title: 'Quiet feet. Questionable handicap.', color: '#6ca3aa', power: .93, speed: 1.23, damage: .95, health: 90, precision: 1.3, weapon: 'Twin blades', special: 'Shadow storm', description: 'Quick across the rough, precise on the green. Disappears after a bogey.', stats: [68, 96, 76] },
  { model: 'monk', selectionClip: 'Naginata_Selection_Idle', combatStyle: 'naginata', motionPrefix: 'Naginata_', readyClip: 'Naginata_Ready', weaponKind: 'naginata', dualWield: false, name: 'The Monk', title: 'At peace with the three-putt', color: '#dcad57', power: 1, speed: .94, damage: 1.4, health: 140, precision: 1.12, weapon: 'Naginata', special: 'Temple thunder', description: 'Unshakable balance and sweeping reach. Enlightenment includes bunker etiquette.', stats: [80, 80, 96] },
  { model: 'kaede', selectionClip: 'Fan_Selection_Idle', combatStyle: 'fan', motionPrefix: 'Fan_', readyClip: 'Fan_Ready', weaponKind: 'jian', dualWield: false, name: 'Kaede', title: 'Grace under pressure', color: '#cc6175', power: 1.05, speed: 1.08, damage: 1.12, health: 105, precision: 1.1, weapon: 'Jian · straight sword', special: 'Petal tempest', description: 'A tour captain with a precise straight sword and graceful countersteps. Her etiquette is sharper than her putting.', stats: [88, 83, 82] },
  { model: 'ayame', selectionClip: 'Ring_Selection_Idle', combatStyle: 'ring', motionPrefix: 'Ring_', readyClip: 'Ring_Ready', weaponKind: 'dao', dualWield: false, name: 'Ayame', title: 'Every opening has an angle', color: '#9e8cce', power: .96, speed: 1.2, damage: 1, health: 95, precision: 1.28, weapon: 'Dao · curved sabre', special: 'Violet orbit', description: 'A match-play tactician with a curved sabre and quick changes of direction. Takes every dogleg personally.', stats: [73, 95, 80] },
  { model: 'sora', selectionClip: 'Sickle_Selection_Idle', combatStyle: 'sickle', motionPrefix: 'Sickle_', readyClip: 'Sickle_Ready', weaponKind: 'wakizashi', dualWield: false, name: 'Sora', title: 'Patient enough to wait. Fast enough to strike.', color: '#6caf9c', power: 1.03, speed: 1, damage: 1.3, health: 125, precision: 1.18, weapon: 'Wakizashi · short sword', special: 'Jade harvest', description: 'A quiet links hunter with a short sword, low footwork, and a dry sense of humor. Always makes the cut.', stats: [84, 88, 91] },
];
